quarkus:
  http:
    port: 8080
    cors: true
  smallrye-openapi:
    info-title: API REST
    info-version: 1.0.0
    info-description: API base for Investors
  swagger-ui:
    always-include: true
  neo4j:
    uri:
      bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j_pw_change_me


smallrye:
  jwt:
    sign:
      key:
        location:
          privateKey.pem
mp:
  jwt:
    verify:
      publickey:
        location:
          publicKey.pem
      issuer: https://goldwaves/auth
      audiences: goldwaves-app
    token:
      header: Authorization